name: Build & deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Build and test with maven
        run: mvn --batch-mode package


