name: Build & deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: maven

      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build the applications
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push


